[package]
name = "SpellChecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = "4.6.0"
serde = "1.0.195"
tree_iterators_rs = "1.2.1"
unicode-segmentation = "1.10.1"
